pipeline {
    agent any

    tools {
        maven 'M11'
    }

    stages {
        stage('Git SCM Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'glpat-_iZhL3dWvohPi2CNZyDc',
                    url: 'https://github.com/ombgr/webserver-deployment.git'
            }
        }

        stage('Build') {
            steps {
                script {
                    withMaven(maven: 'M11') {
                        sh 'mvn clean install package'
                    }
                }
            }
        }

        stage('Publish Over SSH') {
            steps {
                sshPublisher(publishers: [
                    sshPublisherDesc(
                        configName: 'webserver',
                        transfers: [
                            sshTransfer(
                                sourceFiles: 'target/*.war',
                                removePrefix: 'target/',
                                remoteDirectory: '/usr/share/tomcat9/webapps',
                                execCommand: '',
                                execTimeout: 120000,
                                flatten: true,
                                makeEmptyDirs: false,
                                noDefaultExcludes: false,
                                patternSeperator: '[,]+',
                                remoteDirectorySDF: false,
                                usePromotionTimestamp: false,
                                useWorkspaceInPromotion: false,
                                verbose: true
                            )
                        ]
                    )
                ])
            }
        }
    }
}
